### ISSUE TITLE
Write a doc to explain how to contribute to the doc

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia.github.io#203]
Currently, it's very difficult for average users to contribute to the Thelia documentation.

We should write a documentation to explain the tools and techniques used to produce the documentations.

**Comment by acobster** [comment]
I'm happy to take this on. Here's what I'm thinking:

1. Add a section in contribute.md devoted to contributing documentation
2. Describe briefly what Jekyll and Markdown are and link to their respective websites
3. Refer them to the README file for this repo

In addition, we should probably enumerate the CLI tools you need to install (via `npm install -g`) in order to serve the site, and explicitly call out Node/`npm` as a dependency. This is probably better done in the README itself.

The required npm CLI packages look like `bower`, `grunt`, and `jekyll`...am I missing anything?
